name: finance_news
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  url_launcher: ^6.3.1
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

# Uygulama ikonu yapılandırması - Geliştirilmiş ayarlar
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/image/finance_news_app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/image/finance_news_app_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/image/finance_news_app_logo.png"
    background_color: "#FFFFFF"
    theme_color: "#2563EB"  

  assets:
    - assets/image/

